### ISSUE TITLE
"Bus Error" on join

### ISSUE THREAD

**Issue by sticklerer** [multitheftauto/mtasa-blue#2865]
### Describe the bug

I'm keep getting "Bus Error" when i try to join my server.
It's running on a Raspberry Pi 3 A+ on Dietpi (armhf).
The logs from deathmatch shows no indication of the crash.

### Steps to reproduce

1. Download the ARM 32-bit version of MTA Server from https://linux.multitheftauto.com
2. Extract it then download both the config and resources and extract them to the correct folder too
3. Start the server
4. Try to join
5. Bus Error

### Version

Server :  1.5.9-9.21437.0 (Dietpi 32bit)
Client :  1.5.9-release-21503 (Windows 11 64-bit)

### Additional context

![image](https://user-images.githubusercontent.com/48804536/210453501-aea752c7-9fc5-4d1d-baaa-a1c9abfbc3c7.png)
![image](https://user-images.githubusercontent.com/48804536/210453646-63d12b96-b295-4bf0-a6a1-1ccb29904589.png)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by botder** [comment]
I have seen this error, but I never had the time nor experience to debug this issue. It would be great if somebody else could help out here.

**Comment by ruems** [comment]
The "Bus Error" message indicates that the server is unable to access memory properly. Raspberry Pi 3 A+ has limited memory, which may not be enough to run the MTA:SA server smoothly.

It could also could be OS limitations, have you considered switching to a different operating system that is optimized for the Raspberry Pi hardware, such as Raspbian, that may be the best solution.

**Comment by sticklerer** [comment]
I doubt that it's a resource issue since it doesn't use resources at all on idle , it immediately crashes on joining though . The same goes for the OS , dietpi is even more lightweight and running much better then Raspbian . 

I will try Rasbpian and turning of SWAP temporary and let you know the results

**Comment by sticklerer** [comment]
After disabling swap it works fine ,  i will try other OS and see if it's only diepi or others too

**Comment by vahook** [comment]
Bus Error in this case indicates unaligned memory access (which is something you should absolutely avoid doing on ARM), and it happens because [sync structures are packed](https://github.com/multitheftauto/mtasa-blue/blob/7fa778bb22313ac16263421f588ef2ecb9781602/Shared/sdk/net/SyncStructures.h#L31).

For example, here is a backtrace from my RPi 3b+ after trying to join, using the default resources:
```
(gdb) bt
#0  0x75c12dfe in CVehicle::SetPosition(CVector const&) () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#1  0x75c12c76 in CUnoccupiedVehicleSync::Packet_UnoccupiedVehicleSync(CUnoccupiedVehicleSyncPacket&) () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#2  0x75c12d8c in CUnoccupiedVehicleSync::ProcessPacket(CPacket&) () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#3  0x75b2e086 in CGame::ProcessPacket(CPacket&) () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#4  0x75b2e2ae in CGame::StaticProcessPacket(unsigned char, NetServerPlayerID const&, NetBitStreamInterface*, SNetExtraInfo*) () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#5  0x75d578d0 in CNetServerBuffer::ProcessIncoming() () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#6  0x75d57ba4 in CNetServerBuffer::DoPulse() () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#7  0x75b23450 in CGame::DoPulse() () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#8  0x75aa354a in CServer::DoPulse() () from /home/pi/mta/multitheftauto_linux_arm-1.6.0-rc-23320/arm/deathmatch.so
#9  0x76bc8310 in CServerImpl::MainLoop() () from ./arm/core.so
#10 0x76bc8e9c in CServerImpl::Run(int, char**) () from ./arm/core.so
#11 0x76bd9c2e in Run () from ./arm/core.so
#12 0x00401234 in main ()
(gdb) x/2i $pc-4
   0x75c12dfa <_ZN8CVehicle11SetPositionERK7CVector+14>:        vldr    s13, [r1]
=> 0x75c12dfe <_ZN8CVehicle11SetPositionERK7CVector+18>:        vldr    s14, [pc, #88]  @ 0x75c12e58 <_ZN8CVehicle11SetPositionERK7CVector+108>
(gdb) i r
r0             0x157ced8           22531800
r1             0x18fa0cf           26190031
r2             0x0                 0
r3             0x157ced8           22531800
r4             0x18fa0c9           26190025
r5             0x157ced8           22531800
r6             0x1ae6d48           28208456
r7             0x18bcda8           25939368
r8             0x5c65e0            6055392
r9             0x18fa0c8           26190024
r10            0x75f4e93c          1978984764
r11            0x7605f000          1980100608
r12            0x5cffff            6094847
sp             0x7effe988          0x7effe988
lr             0x75c12c77          1975594103
pc             0x75c12dfe          0x75c12dfe <CVehicle::SetPosition(CVector const&)+18>
cpsr           0x30                48
fpscr          0x20000010          536870928
tpidruro       <unavailable>
```
As you can see, the server crashed when it tried to load the `vecPosition` argument of `CVehicle::SetPosition(const CVector& vecPosition)` from the address `0x18fa0cf` (unaligned), when processing an unoccupied vehicle sync packet.

Since disabling packing is not an option, I'm not sure how you would go about fixing this, though.
